[tasks.setup]
script = [
    "grep -q ncm.org /etc/hosts || echo '127.0.0.1 ncm.org' | sudo tee -a /etc/hosts",
    "docker start postgres &>/dev/null || docker run -d --name postgres --net=host postgres:10.3"
]

[tasks.reset]
script = [
    "docker rm -f postgres"
]

[tasks.schema]
script = [
    "diesel print-schema > src/schema.rs --database-url postgres://postgres:postgres@localhost:5432/postgres"
]

[tasks.psql]
script = [
    "docker run --rm -it --net=host postgres:10.3 psql -U postgres -h localhost"
]

[tasks.run]
script = [
    "cargo watch -x run"
]

[tasks.docker]
script = [
    "docker run -v cargo-cache:/root/.cargo -v \"$PWD:/volume\" --rm -it clux/muslrust:nightly-2018-03-02 cargo build --release",
    "docker build . -t pyros2097/ncm:latest"
]
