[tasks.setup]
script = [
    "docker start postgres &>/dev/null || docker run -d --name postgres --net=host postgres:10.3",
    "docker start redis &>/dev/null || docker run -d --name redis --net=host redis:3.2.0"
]

[tasks.reset]
script = [
    "docker rm -f postgres"
]

[tasks.schema]
script = [
    "diesel print-schema > src/schema.rs --database-url postgres://postgres:postgres@localhost:5432/postgres"
]

[tasks.psql]
script = [
    "docker run --rm -it --net=host postgres:10.3 psql -U postgres -h localhost"
]

[tasks.redis-cli]
script = [
    "docker run --rm -it --net=host redis:3.2.0 redis-cli"
]

[tasks.run]
script = [
    "cargo watch -x run"
]
