export default ({
  errs: {
    title: 'Whoops!',
    network: 'Please check your Network Connection',
    username: 'Username is required',
    usernameExists: 'This username is already taken',
    email: 'Email is not valid',
    emailExists: 'This email is already taken',
    password: 'Password should be atleast 6 characters long',
    retypePassword: 'Passwords do not match',
    invalidCredentials: 'Invalid Credentials.',
    userNotFound: 'User does not exist',
  },
  header: {
    save: 'SAVE',
    editProfile: 'Edit Profile',
    settings: 'Settings',
  },
  nav: {
    tabBar: {
      feed: 'FEED',
      activity: 'ACTIVITY',
      explore: 'EXPLORE',
      me: 'ME',
    },
  },
  login: {
    title: 'New Creation Ministry',
    email: 'EMAIL',
    password: 'PASSWORD',
    login: 'Login',
    signUp: 'Dont have an account?',
    getStarted: 'Get started',
    forgot: 'Forgot Password',
    appLoc: 'Looking for the app?',
    download: 'Download here',
  },
  signUp: {
    title: 'SIGNUP',
    username: 'USERNAME',
    name: 'FIRST NAME',
    email: 'EMAIL',
    password: 'PASSWORD',
    signUp: 'SIGN UP',
    termsHeader: 'By creating an account with NCM, you agree to the ',
    termsOfUse: 'Terms of Use',
    and: ' and ',
    privacyPolicy: 'Privacy Policy',
    back: 'BACK',
  },
  forgotPassword: {
    title: 'Forgot Password',
    description: 'Enter your email address and we\'ll send you a link to reset your password',
    email: 'EMAIL',
    submit: 'SUBMIT',
  },
  feed: {
    emptyData: 'Looks like you are no news today.',
  },
});
