version: '2'
services:
  web:
    image: ncm:latest
    build:
      context: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    # fip: 162.221.195.240
    links:
      - postgres
    depends_on:
      - postgres
    ports:
      - "8080:80"
  postgres:
    image: postgres:10.3
